all:  combination

run: project-7a
	./project-7a

build: project-7a.c
	gcc -o project-7a project-7a.c

combination:  project-7a.c
	gcc -o project-7a project-7a.c
	./project-7a
	rm project-7a

clean:
	rm project-7a
